name: demoaiemo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-323.1.beta

dependencies:
  rxdart: ^0.28.0
  flutter_searchable_dropdown: ^2.0.0
  flutter:
    sdk: flutter
  camera: 0.11.0+2 
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  tflite_v2: ^1.0.0
  firebase_auth: ^5.1.2
  http: ^1.2.2
  image: ^4.2.0
  web_socket_channel: ^3.0.1
  firebase_analytics: ^11.2.1
  location: ^7.0.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  intl: any
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.3.0 # Bu ikon kullanmak için eklenmeli
  firebase_storage: ^12.3.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true
  assets: 
  - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icondark.png"  # İkon dosyasının yolunu buraya ekleyin