name: demoaiemo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  cloud_firestore: ^5.1.0
  connect_to_sql_server_directly: ^0.0.1
  firebase_auth: ^5.1.1
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  tflite_flutter: ^0.9.5
  tflite_flutter_helper: ^0.2.1
  tflite_v2: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/
